### ISSUE TITLE
access single ascii artwork

### ISSUE THREAD

**Issue by ad-fabiane** [MaximilianLloyd/ascii.nvim#1]
Hello,

i am really enjoying this plugin, but i would love to have the ability to access a specific ascii.
This also should make it easy to get a random ascii from all artworks.

Just as a idea for the future...

best regards

**Comment by MaximilianLloyd** [comment]
Hi! Great to hear that you are enjoying the plugin. 

You can already access a specific one by referencing the path.

For example:
```lua
local options = {
	header = {
		...
	    val = ascii.art.animals.dogs.lucky,
		...
	},
}
```

If you use the previewer, the path should show up at the top.
![image](https://user-images.githubusercontent.com/10583205/205292319-7cb8a5ab-f59b-441d-a195-462e750d859e.png)

To call the previewer run:
```
lua require("ascii").preview()
```

Let me know if that doesn't work :) 

Great suggestion on getting a globally random art piece though! I'll start working on that.
