### ISSUE TITLE
Can't get it working on lunarvim

### ISSUE THREAD

**Issue by s4ptarshi** [MaximilianLloyd/ascii.nvim#2]
![image](https://user-images.githubusercontent.com/80621081/206933425-1fc0810b-57fc-458c-8fe9-14549f8d680c.png)
giving this error when trying to use it.

**Comment by MaximilianLloyd** [comment]
Hi! I haven't used lunar vim before. But you need to require the plugin before you use it. 
```lua
local ascii = require("ascii")
```

Let me know if that helps.

**Comment by s4ptarshi** [comment]
![image](https://user-images.githubusercontent.com/80621081/207156240-ac143a9d-d98f-4b47-8e3b-26bd0717753c.png)
it's not working. It's giving me this error

**Comment by s4ptarshi** [comment]
nvm got it working, seems like a plugin installation error
